id: I71B4D2FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:45:24+00:00'
last_modified: '2022-06-08T09:55:57.829650+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7920
  title: མདོ་མཁྱེན་བརྩེ་ཡེ་ཤེས་རྡོ་རྗེའི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9BDB:
      image_group_id: I3CN7922
      title: ''
      total_pages: 494
      order: 1
      base_file: 9BDB.txt
    7ADE:
      image_group_id: I3CN7923
      title: ''
      total_pages: 364
      order: 2
      base_file: 7ADE.txt
    '9120':
      image_group_id: I3CN7924
      title: ''
      total_pages: 352
      order: 3
      base_file: 9120.txt
    79ED:
      image_group_id: I3CN7925
      title: ''
      total_pages: 312
      order: 4
      base_file: 79ED.txt
    '7928':
      image_group_id: I3CN7926
      title: ''
      total_pages: 292
      order: 5
      base_file: 7928.txt
    1F64:
      image_group_id: I3CN7927
      title: ''
      total_pages: 328
      order: 6
      base_file: 1F64.txt
    3D32:
      image_group_id: I3CN7928
      title: ''
      total_pages: 336
      order: 7
      base_file: 3D32.txt
    AF77:
      image_group_id: I3CN7929
      title: ''
      total_pages: 324
      order: 8
      base_file: AF77.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
